title: Alexddhuang's Blog
author: Alexander D Huang
email: alexddhuang@gmail.com

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: alxdhuang
    github: alexddhuang
    stackoverflow: "11629344"
    facebook: alexander.huang.3597
    instagram: alexddhuang
    rss: rss

disqus:
  shortname: alexddhuang

google_analytics: UA-141815461-1

show_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page/:num.html"

remote_theme: alexddhuang/minima@alexddhuang

header_pages:
  - categories.md
  - tags.md

copyright: >    
  © <!--copyyears--> <!--author-->; All rights reserved.

mathjax:
  enable: true
  extensions:
    - "cancel.js"
